// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: sim.proto

package sim;

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SimulationClient is the client API for Simulation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SimulationClient interface {
	Broadcast(ctx context.Context, in *BroadcastTxn, opts ...grpc.CallOption) (*AcknowledgementTxn, error)
}

type simulationClient struct {
	cc grpc.ClientConnInterface
}

func NewSimulationClient(cc grpc.ClientConnInterface) SimulationClient {
	return &simulationClient{cc}
}

func (c *simulationClient) Broadcast(ctx context.Context, in *BroadcastTxn, opts ...grpc.CallOption) (*AcknowledgementTxn, error) {
	out := new(AcknowledgementTxn)
	err := c.cc.Invoke(ctx, "/sim.Simulation/Broadcast", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SimulationServer is the server API for Simulation service.
// All implementations must embed UnimplementedSimulationServer
// for forward compatibility
type SimulationServer interface {
	Broadcast(context.Context, *BroadcastTxn) (*AcknowledgementTxn, error)
	mustEmbedUnimplementedSimulationServer()
}

// UnimplementedSimulationServer must be embedded to have forward compatible implementations.
type UnimplementedSimulationServer struct {
}

func (UnimplementedSimulationServer) Broadcast(context.Context, *BroadcastTxn) (*AcknowledgementTxn, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Broadcast not implemented")
}
func (UnimplementedSimulationServer) mustEmbedUnimplementedSimulationServer() {}

// UnsafeSimulationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SimulationServer will
// result in compilation errors.
type UnsafeSimulationServer interface {
	mustEmbedUnimplementedSimulationServer()
}

func RegisterSimulationServer(s grpc.ServiceRegistrar, srv SimulationServer) {
	s.RegisterService(&Simulation_ServiceDesc, srv)
}

func _Simulation_Broadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastTxn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationServer).Broadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sim.Simulation/Broadcast",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationServer).Broadcast(ctx, req.(*BroadcastTxn))
	}
	return interceptor(ctx, in, info, handler)
}

// Simulation_ServiceDesc is the grpc.ServiceDesc for Simulation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Simulation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sim.Simulation",
	HandlerType: (*SimulationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Broadcast",
			Handler:    _Simulation_Broadcast_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sim.proto",
}
